package com.yuzhou.openai.api.completion;

import com.yuzhou.openai.api.Message;
import lombok.Data;

/**
 * A completion generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
@Data
public class CompletionChoice {
    /**
     * The generated text. Will include the prompt if {@link CompletionRequest#echo } is true
     */
    private String text;

    /**
     * This index of this completion in the returned list.
     */
    private Integer index;

    /**
     * The log probabilities of the chosen tokens and the top {@link CompletionRequest#logprobs} tokens
     */
    private LogProbResult logprobs;

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    private String finish_reason;

    private Message message;
}
